dist: trusty
sudo: required
language: clojure
before_script:
  - sudo test/install_deps.sh
  - sudo test/start_mesos.sh
script:
  - lein travis
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk6
  #- openjdk7

notifications:
  email:
      - oubiwann@gmail.com
